import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import seGoeUiFont from '@/configs/font.config';
import { LayoutClient } from '@/layouts';
import AppProvider from '@/provider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={seGoeUiFont.className} id='app'>
        <AntdRegistry>
          <AppProvider>
            <LayoutClient>{children}</LayoutClient>
          </AppProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
